### ISSUE TITLE
ParseError for "finally"

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#34]
I'm getting a ParseError for finally in 
  try {
  ...
  } catch {
  ....
  } finally {
  ...
  }

**Comment by vic** [comment]
The parser doesn't implement catch without "catch condition" part. Will implement that to default to be the same than "catch Object { ... }"

**Comment by bakkdoor** [comment]
ok cool.

**Comment by vic** [comment]
Fixed try with empty class condition. defaults to Object. Closed by 78fd4bf9f28f806c44b222c9a238ac5525253457

**Comment by bakkdoor** [comment]
Still getting a parse error for tests/exceptions.fy:

Caused by: Parse error at line 57, unexpected token: "finally" (Fancy::Parser::ParseError)

**Comment by vic** [comment]
Fixed http://github.com/bakkdoor/fancy/commit/4bd360a2d53d2d18fa8aeef92b3d96dd527e9041
